# Generated by Django 5.2.3 on 2025-06-10 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrievanceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=True, verbose_name='Primary Officer')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='GrievanceFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Grievance Flow',
                'verbose_name_plural': 'Grievance Flows',
            },
        ),
        migrations.CreateModel(
            name='GrievanceStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='GrievanceTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('WRONG_DEPT', 'Wrong Department'), ('EXPERTISE', 'Specialized Expertise'), ('ESCALATION', 'Higher Authority Needed')], max_length=20)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-transferred_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficerIDTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_used', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hod', models.BooleanField(default=False, help_text='Set this if the officer is the department HOD', verbose_name='Head of Department')),
            ],
            options={
                'verbose_name': 'Officer Profile',
                'verbose_name_plural': 'Officer Profiles',
            },
        ),
        migrations.CreateModel(
            name='FlowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('INITIAL', 'Initial Assignment'), ('TRANSFER', 'Department Transfer'), ('RESOLUTION', 'Final Resolution')], max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.department')),
            ],
            options={
                'verbose_name': 'Flow Stage',
                'verbose_name_plural': 'Flow Stages',
                'ordering': ['start_date'],
            },
        ),
    ]
