# Generated by Django 5.2.3 on 2025-06-10 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_app', '0001_initial'),
        ('grievance_app', '0001_initial'),
        ('officer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flowstage',
            name='officer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'OFFICER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grievanceassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grievanceassignment',
            name='grievance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='grievance_app.grievance'),
        ),
        migrations.AddField(
            model_name='grievanceassignment',
            name='officer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'OFFICER'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grievanceflow',
            name='current_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_grievances', to='core_app.department'),
        ),
        migrations.AddField(
            model_name='grievanceflow',
            name='current_officer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'OFFICER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grievanceflow',
            name='grievance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flow', to='grievance_app.grievance'),
        ),
        migrations.AddField(
            model_name='flowstage',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='officer.grievanceflow'),
        ),
        migrations.AddField(
            model_name='grievancestatuslog',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grievancestatuslog',
            name='grievance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='grievance_app.grievance'),
        ),
        migrations.AddField(
            model_name='grievancetransfer',
            name='from_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_transfers', to='core_app.department'),
        ),
        migrations.AddField(
            model_name='grievancetransfer',
            name='grievance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='grievance_app.grievance'),
        ),
        migrations.AddField(
            model_name='grievancetransfer',
            name='to_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_transfers', to='core_app.department'),
        ),
        migrations.AddField(
            model_name='grievancetransfer',
            name='transferred_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='officeridtracker',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core_app.department'),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.department', verbose_name='Assigned Department'),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'OFFICER'}, on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
        migrations.AlterUniqueTogether(
            name='grievanceassignment',
            unique_together={('grievance', 'officer')},
        ),
        migrations.AddConstraint(
            model_name='officerprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_hod', True)), fields=('department',), name='unique_hod_per_department'),
        ),
    ]
