# Generated by Django 5.2.3 on 2025-06-10 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_address', models.TextField(verbose_name='Office Address')),
                ('collector_id', models.CharField(max_length=20, unique=True, verbose_name='Collector ID')),
                ('tenure_start', models.DateField(verbose_name='Tenure Start Date')),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core_app.district', verbose_name='Administered District')),
            ],
            options={
                'verbose_name': 'Collector Profile',
                'verbose_name_plural': 'Collector Profiles',
            },
        ),
    ]
