# Generated by Django 5.2.3 on 2025-06-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile image for the collector.', null=True, upload_to='collector_profiles/', verbose_name='Profile Picture'),
        ),
    ]
