# Generated by Django 5.2.3 on 2025-06-10 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('code', models.CharField(help_text='Official district code (e.g. KL-01)', max_length=3, primary_key=True, serialize=False, verbose_name='District Code')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='District Name')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Department Code')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Department Name')),
                ('district', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core_app.district', verbose_name='Department District')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
    ]
