# Generated by Django 5.2.3 on 2025-06-11 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Address')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, verbose_name='Gender')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('thaluk', models.CharField(max_length=100, verbose_name='Thaluk')),
                ('village', models.CharField(max_length=100, verbose_name='Village')),
                ('panchayath', models.CharField(max_length=100, verbose_name='Panchayath')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'PUBLIC'}, on_delete=django.db.models.deletion.CASCADE, related_name='public_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Public User Profile',
                'verbose_name_plural': 'Public User Profiles',
            },
        ),
    ]
