# Generated by Django 5.2.3 on 2025-06-11 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_alter_department_unique_together_and_more'),
        ('user', '0002_publicuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicuserprofile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.district', verbose_name='District'),
        ),
    ]
