# Generated by Django 5.2.3 on 2025-06-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_publicuserprofile_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('last_used', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
