# Generated by Django 5.2.3 on 2025-06-10 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grievance_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Grievance ID')),
                ('date_filed', models.DateTimeField(auto_now_add=True, verbose_name='Filing Date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('description', models.TextField(verbose_name='Detailed Description')),
                ('source', models.CharField(choices=[('WEB', 'Website'), ('MOBILE', 'Mobile App'), ('OFFICE', 'Office Visit'), ('EMAIL', 'Email')], max_length=20, verbose_name='Source Channel')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated')], default='PENDING', max_length=20, verbose_name='Current Status')),
                ('priority', models.CharField(choices=[('LOW', 'Low (30 days)'), ('MEDIUM', 'Medium (15 days)'), ('HIGH', 'High (7 days)'), ('CRITICAL', 'Critical (3 days)')], default='MEDIUM', max_length=20, verbose_name='Priority Level')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Resolution Due Date')),
                ('applicant_name', models.CharField(default='N/A', max_length=100, verbose_name='Applicant Name')),
                ('applicant_address', models.TextField(default='N/A', help_text='Provide full residential address', verbose_name='Applicant Address')),
                ('contact_number', models.CharField(default='0000000000', max_length=15, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.department', verbose_name='Responsible Department')),
                ('district', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core_app.district', verbose_name='Department District')),
            ],
            options={
                'verbose_name': 'Public Grievance',
                'verbose_name_plural': 'Public Grievances',
                'ordering': ['-date_filed'],
                'indexes': [models.Index(fields=['status'], name='grievance_a_status_a450f3_idx'), models.Index(fields=['priority'], name='grievance_a_priorit_2bc567_idx'), models.Index(fields=['due_date'], name='grievance_a_due_dat_cda8c6_idx')],
            },
        ),
    ]
